package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val CandyPrimary = Color(0xFF6750A4)
val CandySecondary = Color(0xFF625B71)
val CandyTertiary = Color(0xFF7D5260)
val CandyBackground = Color(0xFFFEF7FF)
val CandyOnBackground = Color(0xFF1D1B20)
val CandySurface = Color(0xFFFFFFFF)
val CandyOnSurface = Color(0xFF1D1B20)
val CandySurfaceVariant = Color(0xFFE7E0EC)
val CandyOnSurfaceVariant = Color(0xFF49454F)
val CandyPrimaryContainer = Color(0xFFEADDFF)
val CandyOnPrimaryContainer = Color(0xFF21005D)
val CandySecondaryContainer = Color(0xFFE8DEF8)
val CandyOnSecondaryContainer = Color(0xFF1D192B)
val CandyTertiaryContainer = Color(0xFFFFD8E4)
val CandyOnTertiaryContainer = Color(0xFF31111D)
val CandyError = Color(0xFFB3261E)
val CandyOutline = Color(0xFF79747E)
val CandyOutlineVariant = Color(0xFFCAC4D0)
val CandyNavBarBackground = Color(0xFFF3EDF7)
val SoftGreenCompleted = Color(0xFFE6F4EA)
val DarkGreenText = Color(0xFF1E8E3E)
